### ISSUE TITLE
Unable to start with docker-compose due to connection refused

### ISSUE THREAD

**Issue by vijamesDD** [camunda-community-hub/zeebe-simple-tasklist#169]
Hi, I'm trying to run this simple tasklist locally using the docker compose instructions and I get a connectivity error between the tasklist worker and zeebe broker. 

Using the latest `main` branch, when I run this docker compose command
`docker-compose --profile in-memory up`

I get this error

```
zeebe-simple-tasklist-in-memory  | 2023-05-04 11:01:15.174  WARN 1 --- [ault-executor-2] io.camunda.zeebe.client.job.poller       : Failed to activate jobs for worker zeebe-simple-tasklist and job type io.camunda.zeebe:userTask
zeebe-simple-tasklist-in-memory  |
zeebe-simple-tasklist-in-memory  | io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
zeebe-simple-tasklist-in-memory  | 	at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.45.1.jar:1.45.1]
zeebe-simple-tasklist-in-memory  | 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) ~[grpc-stub-1.45.1.jar:1.45.1]
zeebe-simple-tasklist-in-memory  | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562) ~[grpc-core-1.45.1.jar:1.45.1]
zeebe-simple-tasklist-in-memory  | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) ~[grpc-core-1.45.1.jar:1.45.1]
zeebe-simple-tasklist-in-memory  | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743) ~[grpc-core-1.45.1.jar:1.45.1]
zeebe-simple-tasklist-in-memory  | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722) ~[grpc-core-1.45.1.jar:1.45.1]
zeebe-simple-tasklist-in-memory  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.45.1.jar:1.45.1]
zeebe-simple-tasklist-in-memory  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.45.1.jar:1.45.1]
zeebe-simple-tasklist-in-memory  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
zeebe-simple-tasklist-in-memory  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
zeebe-simple-tasklist-in-memory  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
zeebe-simple-tasklist-in-memory  | Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: zeebe/172.19.0.2:26500
zeebe-simple-tasklist-in-memory  | Caused by: java.net.ConnectException: Connection refused
zeebe-simple-tasklist-in-memory  | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
zeebe-simple-tasklist-in-memory  | 	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[na:na]
zeebe-simple-tasklist-in-memory  | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[na:na]
zeebe-simple-tasklist-in-memory  | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
zeebe-simple-tasklist-in-memory  | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
zeebe-simple-tasklist-in-memory  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
zeebe-simple-tasklist-in-memory  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
zeebe-simple-tasklist-in-memory  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
zeebe-simple-tasklist-in-memory  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
zeebe-simple-tasklist-in-memory  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.79.Final.jar:4.1.79.Final]
zeebe-simple-tasklist-in-memory  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.79.Final.jar:4.1.79.Final]
zeebe-simple-tasklist-in-memory  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.79.Final.jar:4.1.79.Final]
zeebe-simple-tasklist-in-memory  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

Is anyone able to provide suggestions as to how to fix? I'm using the docker compose file from this repository https://github.com/camunda-community-hub/zeebe-simple-tasklist/blob/main/docker/docker-compose.yml

Perhaps I am missing some other setup that is required? Thanks very much

**Comment by saig0** [comment]
@vijamesDD thank you for reporting. :+1: 

It is working for me. :thinking:  
Please share the complete console output from Docker and details about your environment.
